coverage:
  status:
    project:
      default:
        target: 80  # Align with Sonar coverage requirement
        threshold: 2.0
    patch:
      default:
        informational: true

ignore:
  - "tools/build_skill.py"  # Build script tested via CI artifact generation
