coverage:
  status:
    project:
      default:
        target: 80  # Align with Sonar coverage requirement
        threshold: 2.0
    patch:
      default:
        informational: true

  # 個別ファイルのカバレッジ最低値（ローカルではtools/check_coverage_per_file.pyで検証）
  precision: 2
  round: down

ignore:
  - "tools/build_skill.py"  # Build script tested via CI artifact generation
  - "tools/check_coverage_per_file.py"  # Coverage check script itself
  - "**/__init__.py"  # Import-only files
